name: biteful
description: "Biteful - Food delivery app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  go_router: ^14.6.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  sqflite: ^2.4.1
  path: ^1.9.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  timezone: ^0.9.4
  shimmer: ^3.0.0
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#284B63"
  adaptive_icon_foreground: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Mogra
      fonts:
        - asset: assets/fonts/Mogra-Regular.ttf
